kind: pipeline
type: docker
name: linux-arm

platform:
  os: linux
  arch: arm 

steps:
- name: dockerhub 
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    repo: registry.hub.docker.com/nedaya/dockerhub-description
    registry: registry.hub.docker.com
    auto_tag_suffix: linux-arm
    auto_tag: true
    squash: true

---    
kind: pipeline
type: docker
name: linux-arm64

platform:
    arch: arm64 
steps:      
- name: dockerhub 
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    repo: registry.hub.docker.com/nedaya/dockerhub-description
    registry: registry.hub.docker.com
    auto_tag_suffix: linux-arm64
    auto_tag: true
    squash: true
---    
kind: pipeline
type: docker
name: linux-amd64

platform:
    arch: amd64 
steps:      
- name: dockerhub 
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    repo: registry.hub.docker.com/nedaya/dockerhub-description
    registry: registry.hub.docker.com
    auto_tag_suffix: linux-amd64
    auto_tag: true
    squash: true
    
    
---
kind: pipeline
type: docker
name: manifest

platform:
  arch: arm64 

steps:
- name: publish
  image: plugins/manifest:1.2
  settings:
    auto_tag: true
    ignore_missing: true
    spec: docker/manifest.tmpl
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
- name: readme
  image: nedaya/dockerhub-description:2
  environment:
    DOCKERHUB_USERNAME:
      from_secret: dockerhub_username
    DOCKERHUB_PASSWORD:
      from_secret: dockerhub_password
    DOCKERHUB_REPOSITORY: nedaya/dockerhub-description    
    README_FILEPATH: README.md
    SHORT_DESCRIPTION: "Crossplatform image of peterevans/dockerhub-description:2"
  commands:
    - node /index.js 
trigger:
  event:
  - push
  - tag

depends_on:
- linux-amd64
- linux-arm64
- linux-arm